-- Add extra student fields used for report generation
ALTER TABLE students
  ADD COLUMN registration_no VARCHAR(100) NULL,
  ADD COLUMN university_reg_no VARCHAR(100) NULL,
  ADD COLUMN roll_no VARCHAR(100) NULL,
  ADD COLUMN program_name VARCHAR(255) NULL,
  ADD COLUMN academic_year VARCHAR(50) NULL,
  ADD COLUMN batch_year VARCHAR(50) NULL,
  ADD COLUMN semester VARCHAR(50) NULL,
  ADD COLUMN rotation_name VARCHAR(255) NULL,
  ADD COLUMN rotation_start_date DATE NULL,
  ADD COLUMN rotation_end_date DATE NULL,
  ADD COLUMN dob DATE NULL,
  ADD COLUMN gender VARCHAR(20) NULL,
  ADD COLUMN blood_group VARCHAR(10) NULL,
  ADD COLUMN phone VARCHAR(30) NULL,
  ADD COLUMN address TEXT NULL,
  ADD COLUMN guardian_name VARCHAR(255) NULL,
  ADD COLUMN guardian_phone VARCHAR(30) NULL,
  ADD COLUMN emergency_contact_name VARCHAR(255) NULL,
  ADD COLUMN emergency_contact_phone VARCHAR(30) NULL,
  ADD COLUMN adviser_name VARCHAR(255) NULL,
  ADD COLUMN hod_name VARCHAR(255) NULL,
  ADD COLUMN principal_name VARCHAR(255) NULL,
  ADD COLUMN remarks TEXT NULL;
